# -*- coding: utf-8 -*-
"""Gold Challenge

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsApztz-Ez4O0_-go1qMpImlkUwsB99H
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

data = pd.read_csv('data.csv', encoding='latin-1')
print (data)

data.info

data.shape

data.columns

import pandas as pd

def cleansing(text):

    cleaned_text = text.lower()
    return cleaned_text

data['Text_Clean'] = data['Tweet'].apply(cleansing)

data.head()

data.isna().sum()

data.loc[data.duplicated(keep=False)].sort_values('Tweet')

data['total_char'] = data['Tweet'].apply(len)

data['total_word'] = data['Tweet'].apply(lambda sent: len(sent.split()))

data.head()

data.isna().sum()/data.shape[0]

data.isna().sum()/data.shape[0]

columns_to_delete = ['Text_Clean']

data.drop(columns=columns_to_delete, inplace=True)

data.head()

pip install sastrawi

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

import re
def lowercase(text):
    lower_text = text.lower()
    return lower_text

def remove_user(text):
    text = re.sub('user', ' ', text)
    text = re.sub(' +', ' ', text)
    return text

def clean_text(text):
    text = re.sub('[0-9]+', ' ', text)
    text = re.sub(r'^RT[\s]+', ' ', text)
    text = re.sub(r'^rt[\s]+', ' ', text)
    text = re.sub('\n',' ', text)
    text = re.sub(r'#', ' ', text)
    text = re.sub('[^0-9a-zA-Z]',' ', text)
    text = text.strip()
    text = re.sub(' +',' ', text)
    text = re.sub(r'[^\w\s]',' ',text)
    return text

def remove_emoticon(text):
    text = text.replace(' \ ', ' ')
    text = re.sub('x..', ' ', text)
    text = re.sub(' n ', ' ', text)
    text = re.sub('\+', ' ', text)
    text = re.sub(' +',' ', text)
    text = re.sub(r'\$\w*',' ',text)
    return text

def stemming(text):
    return stemmer.stem(text)

def cleansing(text):
    text = lowercase(text)
    text = remove_user(text)
    text = clean_text(text)
    text = remove_emoticon(text)
    text = stemming(text)
    return text

for text in data['Tweet']:
    print(cleansing(text))

print("Before cleansing:", data.shape)
data['Tweet'] = data['Tweet'].apply(cleansing)
print("After cleansing:", data.shape)

sample_text = data['Tweet'].iloc[0]
cleansed_sample = cleansing(sample_text)
print("Original Text:", sample_text)
print("Cleansed Text:", cleansed_sample)

print(data.head())

data['Tweet'] = data['Tweet'].apply(cleansing)

data.head(8)

data.head()

data['HS'].value_counts()

data['Abusive'].value_counts()

data.isna().sum()

data.isna().sum()/data.shape[0]

data.mean()

data.median()

pip install matplotlib

from matplotlib import pyplot as plt

data['HS'].value_counts().plot(kind='pie', figsize=(4,4), autopct='%1.f%%', startangle=90, shadow=True)

plt.legend(['NO', 'YES'])
plt.title('Kelompok Tweet Berdasarkan Hate Speech Pada Dataset Twitter')

plt.show()

data['Abusive'].value_counts().plot(kind='pie', figsize=(4,4), autopct='%1.f%%', startangle=90, shadow=True)

plt.legend(['NO', 'YES'])
plt.title('Kelompok Tweet Berdasarkan Abusive Pada Dataset Twitter')

plt.show()

data.loc[:,"HS_Weak":"HS_Strong"].sum()

Tipe_Kekuatan_HS = ('HS_WEAK', 'HS_MODERATE', 'HS_STRONG')
Jumlah_HS = (3383, 1705, 473)
my_color = 'navy', 'blue', 'lightblue'

plt.figure(figsize=(4,5))
plt.bar(Tipe_Kekuatan_HS, Jumlah_HS, color=my_color)


plt.title('Tipe Kekuatan Hate Speech', size=12)
plt.ylabel('Jumlah Hate Speech', size=10)
plt.xlabel('Jumlah Hate Speech', size=10)
plt.xticks(size=8)
plt.yticks(size=8)

plt.show()

data.loc[:,"HS_Individual":"HS_Group"].sum()

Tipe_Kelompok_HS = ('HS_INDIVIDUAL', 'HS_GROUP')
Jumlah_HS = (3575, 1986)
my_color = 'yellowgreen', 'navy',

plt.figure(figsize=(4,5))
plt.bar(Tipe_Kelompok_HS, Jumlah_HS, color=my_color)


plt.title('Tipe Hate Speech Berdasarkan Kelompok', size=10)
plt.ylabel('Jumlah Hate Speech', size=10)
plt.xlabel('Tipe Kelompok', size=10)
plt.xticks(size=8)
plt.yticks(size=8)

plt.show()

"Religion", "Race", "Physical", "Gender", "Other"

data.loc[:,"HS_Religion":"HS_Other"].sum()

Jenis_HS = ("Religion", "Race", "Physical", "Gender", "Other")
Jumlah_HS = (793, 566, 323, 3046, 3740)
my_color = 'navy'

plt.figure(figsize=(4,5))
plt.bar(Jenis_HS, Jumlah_HS, color=my_color)


plt.title('Tipe Hate Speech Berdasarkan Kelompok', size=10)
plt.ylabel('Jumlah Hate Speech', size=10)
plt.xlabel('Jenis Hate Speech', size=10)
plt.xticks(size=8)
plt.yticks(size=8)

plt.show()

pip install wordcloud

from wordcloud import WordCloud

wordcloud = WordCloud(width=1600, height=800, max_font_size=200, background_color='maroon')

text =' '.join(map(str, data['Tweet']))
wordcloud.generate(text)

plt.imshow(wordcloud)
plt.axis("off")
plt.show()